basic.showString("RECIEVER")
radio.setGroup(125)
serial.writeLine("Acceleration")
//  def on_received_number(receivedNumber):
//      led.toggle(4, 4)
//      serial.write_value("z", receivedNumber)
//      serial.write_value("y", receivedNumber)
//      serial.write_value("x", receivedNumber)
//      serial.write_value("zx", receivedNumber)
//      serial.write_value("xy", receivedNumber)
//      serial.write_line(str(input.compass_heading()))
//  radio.on_received_number(on_received_number)
radio.onReceivedValue(function on_received_value(name: string, value: number) {
    led.toggle(4, 4)
    serial.writeValue(name, value)
})
